/*
 * This file is generated by jOOQ.
 */
package cn.zenliu.jooq.ext.model;


import cn.zenliu.jooq.ext.model.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test.test</code>.
     */
    public static final Test TEST_ = cn.zenliu.jooq.ext.model.tables.Test.TEST_;
}
